require:
  rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.1
  Exclude:
    - "bin/*"
    - "lib/**/*"
    - "config/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "Vagrantfile"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - "Gemfile"