version: "3.7"

x-rails_template: &rails_template
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    target: production
  image: rails-production:1.0.0

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - "./.dockerdev/env/db.env"
    ports:
      - "3306:3306"

  app:
    <<: *rails_template
    ports:
      - "3000:3000"
    env_file:
      - "./.dockerdev/env/app.prod.env"
    depends_on:
      - db
      - redis
      - minio
    stdin_open: true
    tty: true

  sidekiq:
    <<: *rails_template
    command: bundle exec sidekiq
    volumes:
      - .:/app_home
    depends_on:
      - db
      - redis
    env_file:
      - "./.dockerdev/env/sidekiq.env"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    command: server /export
    volumes:
      - minio-data:/export
    ports:
      - "9000:9000"
    env_file:
      - "./.dockerdev/env/minio.env"

volumes:
  minio-data:
  mysql-data:
  redis-data:
