version: "3.7"

x-rails_template: &rails_template
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    target: production
  image: rails-production:1.0.0

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    env_file:
      - "./.dockerdev/env/db.env"
    ports:
      - "3306:3306"

  app:
    <<: *rails_template
    ports:
      - "3000:3000"
    env_file:
      - "./.dockerdev/env/app.prod.env"
    depends_on:
      - db
    stdin_open: true
    tty: true
