version: "3.7"

x-rails_template: &rails_template
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    target: dev
  image: rails-dev:1.0.0

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - "./.dockerdev/env/db.env"
    ports:
      - "3306:3306"

  app:
    <<: *rails_template
    command: ash -c "rm -f tmp/pids/server.pid && rm -rf tmp/cache && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_home
    ports:
      - "3000:3000"
    env_file:
      - "./.dockerdev/env/app.env"
    depends_on:
      - db
      - chrome
      - minio
    stdin_open: true
    tty: true

  webpacker:
    <<: *rails_template
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app_home
    ports:
      - "3035:3035"
    env_file:
      - "./.dockerdev/env/webpaker.env"

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - 4444:4444
      - 5900:5900

  minio:
    image: minio/minio:latest
    command: server /export
    volumes:
      - minio-data:/export
    ports:
      - "9000:9000"
    env_file:
      - "./.dockerdev/env/minio.env"

volumes:
  minio-data:
  mysql-data:

